#!/usr/bin/env python3

import json
import sys
from subprocess import Popen, PIPE

change = sys.argv[2]

for x in range(len(sys.argv)):
    if sys.argv[x] == "--change":
        change = sys.argv[x + 1]
        break

if not change.startswith("I"):
    change = 'I' + change.split('~I')[-1]
else:
    change = change.split('~I')[-1] if '~I' in change else change

username = "admin"
server = "localhost"

results = Popen(
    ["ssh", "-p", "29418", f"{username}@{server}", "gerrit", "query",
     "--format", "JSON", "--all-approvals", change],
    stdout=PIPE
).communicate()[0]

results_lines = results.split(b"\n")
for line in results_lines:
    if line.strip() and b'"type":"stats"' not in line:
        parsed = json.loads(line)
        break
else:
    print("No valid change data found")
    sys.exit(1)

verified_min = 0
reviewed_min = 2

verified_count = 0
reviewed_count = 0
print(parsed)
commit = parsed["patchSets"][-1]["revision"]
if not parsed["patchSets"][-1].get("approvals"):
    sys.exit(0)

for approval in parsed["patchSets"][-1]["approvals"]:
    if approval["type"] == "Verified":
        verified_count += int(approval["value"])
    elif approval["type"] == "Code-Review":
        reviewed_count += int(approval["value"])

if verified_count >= verified_min and reviewed_count >= reviewed_min:
    Popen(
        ["ssh", "-p", "29418", f"{username}@{server}", "gerrit",
         "review", "--submit", commit],
        stdout=PIPE
    ).communicate()
